6 - Get comments for a particular article
HaylzRandom/be-nc-news pull request #5
Opened 2023-10-03 10:51 UTC by HaylzRandom

Created endpoint for getting comments for a particular article.

Unable to test for an article that does not exist.

Using promises to get the articleById and to get the comments and would assume that it would return message about article not existing but the comments promise resolves/rejects first 99.9% of the time so it states that no comments exist (which technically is true but not very user friendly)

Spoke to Poonam about it but not heard anything back and don't want to be stuck on a single test not passing due to race conditions

2023-10-03 13:33 UTC, roisinoreilly requested changes
really great work so far! I have a couple of things I'd like you to implement before approving, once you've sorted them send us another PR 😄 

- [x] implement a test for 400 invalid article id
- [x] change where you're rejecting your promise to give a 404 to a 200
- [x] check if .toBeSorted by needs arguments for line 200 of your test (if it doesn't ignore me)
- [x] try using .toMatchObject or .objectContaining and expect.any to look at the shape of objects rather than checking all the types of the properties
- [ ] maybe start to think at this point about splitting your models and controllers into different files eg. articles, topics, comments etc.

2023-10-03 13:33 UTC, roisinoreilly commented on __tests__/app.test.js
> +        expect(comments).toBeSortedBy;
I'm not sure this works without being invoked with something, I know .toBeSorted by itself does but I'm not sure for .toBeSortedBy?

2023-10-03 13:33 UTC, roisinoreilly commented on __tests__/app.test.js
> +          expect(typeof comment.comment_id).toBe('number');
expect.objectContaining would be better and a bit clearer here than checking the type of all these properties

2023-10-03 13:33 UTC, roisinoreilly commented on __tests__/app.test.js
> +        expect(comments).toBeSortedBy('created_at', {
perfect

2023-10-03 13:33 UTC, roisinoreilly commented on __tests__/app.test.js
> +  test('GET:404 should respond with appropriate message and status code when article exists but has no comments', () => {
this should be a 200 not a 404 since it is a valid request that's completed without error

2023-10-03 13:33 UTC, roisinoreilly commented on db/seeds/utils.js
> +exports.checkExists = (table, column, value) => {
really nicely done

2023-10-03 13:33 UTC, roisinoreilly commented on models/comments.model.js
> +      return checkExists('articles', 'article_id', article_id).then(() => {
perfectly done! (except it's a 404 not a 200 but otherwise really nice)

2023-10-04 08:04 UTC, Beth-McCormack approved these changes

2023-10-04 09:04 UTC, merged